# Generated by Django 4.1.5 on 2023-01-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackEndSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
            options={
                'verbose_name': 'Back end skill',
                'verbose_name_plural': 'Back end skills',
            },
        ),
        migrations.CreateModel(
            name='FrontEndSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
            options={
                'verbose_name': 'Front end skill',
                'verbose_name_plural': 'Front end skills',
            },
        ),
    ]
