# Generated by Django 4.1.5 on 2023-01-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=50)),
                ('view_description', models.CharField(max_length=500)),
                ('view_image', models.ImageField(upload_to='detailed_views')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'detailed descriptions',
            },
        ),
        migrations.CreateModel(
            name='TechonologiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'techonology',
                'verbose_name_plural': 'techonologies',
            },
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('project_image', models.ImageField(upload_to='projects')),
                ('project_url', models.URLField(max_length=300)),
                ('detailed_descriptions', models.ManyToManyField(to='projects.projectsdescriptionmodel')),
                ('technologies', models.ManyToManyField(to='projects.techonologiesmodel')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
